# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b82f79dc7124255e373a59a6e0aeef80"
name = "B2B Companion"
application_url = "https://b2b-companion.selling.workers.dev/auth"
embedded = true

[webhooks]
api_version = "2026-04"

[webhooks.privacy_compliance]
customer_deletion_url       = "https://b2b-companion.selling.workers.dev/webhooks"
customer_data_request_url   = "https://b2b-companion.selling.workers.dev/webhooks"
shop_deletion_url           = "https://b2b-companion.selling.workers.dev/webhooks"

[[webhooks.subscriptions]]
topics = [
  "app/uninstalled",
  "app/scopes_update",
  "shop/update",
]
uri = "https://b2b-companion.selling.workers.dev/webhooks"

[[webhooks.subscriptions]]
topics = [
  "companies/create",
  "companies/update",
  "companies/delete",
  "company_locations/create",
  "company_locations/update",
]
uri = "https://b2b-companion.selling.workers.dev/webhooks"

[[webhooks.subscriptions]]
topics = [
  "customers/create",
  "customers/update",
]
uri = "https://b2b-companion.selling.workers.dev/webhooks"

[[webhooks.subscriptions]]
topics = [
  "orders/create",
  "orders/updated",
  "orders/cancelled",
]
uri = "https://b2b-companion.selling.workers.dev/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,write_companies,read_customers,write_customers,read_files,write_files,read_locales,read_markets,read_orders,write_orders,read_payment_terms,write_payment_terms,read_products,write_products,read_shipping,write_shipping,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://b2b-companion.selling.workers.dev/auth/callback" ]

[app_proxy]
url = "https://b2b-companion.selling.workers.dev/proxy"
subpath = "b2b"
prefix = "apps"
